config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
resources :competitions do
    collection do
      get :autocomplete
    end
  end
  resources :competitions do
    member do
      get :participants
    end
  end

match "meetings/register" => "meetings#register", :via => :post

devise_for :users, controllers: { sessions: "users/sessions",registrations: "users/registrations",confirmations: "users/confirmations",passwords: "users/passwords",unlocks: "users/unlocks" }
resources :users, :only => [:show] 

  match '/users/:id/attending_competitions', :to => 'users#attending_competitions', :via => [:get,:post] , as: 'attending_competitions'
  match '/users/:id/created_competitions', :to => 'users#created_competitions', :via => [:get,:post] , as: 'created_competitions'

  root 'pages#home'

  resources :meetings,       only: [:create, :destroy]

end

app/models/competition.rb
class Competition < ActiveRecord::Base

	searchkick text_start: [:name,:collegename,:category],autocomplete: ['name','collegename','category']
=begin
	def self.facets_search(params)
	  query = params[:query].presence || "*"
	  conditions = {}
	  conditions[:year] = params[:year] if params[:year].present?

	  movies = Movie.search query, where: conditions, 
	    facets: [:year], 
	    smart_facets: true, page: params[:page], suggest: true, highlight: true,
	    per_page: 10
	  movies
	end
=end
	geocoded_by :location
	after_validation :geocode, :if => :location_changed?

	def self.facets_search(params)
		query = params[:query].presence || "*"
		conditions = {}
		conditions[:category] = params[:category] if params[:category].present?

		competitions = Competition.search(query,where: conditions,
		 facets: [:category],
		 smart_facets: true, 
		 page: params[:page], per_page: 40)

		competitions
	end


	validates :name,  presence: true, length: { maximum: 50 }
	validates :description,  presence: true, length: { maximum: 50 }
	validates :startDateText,  presence: true
	validates :category,  presence: true

	belongs_to :user 
	has_many :meetings, class_name:  "Meeting", foreign_key: "attending_competition_id"
	has_many :participants, through: :meetings,:source => :participant


end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  after_filter :store_location
  before_action :set_competition, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show , :autocomplete] 
  before_action :correct_user, only: [:edit, :update, :destroy]
  respond_to :html, :json 

  def autocomplete
    #render json: Competition.search(params[:query], fields: [{name: :text_start}], limit: 10).map {|competition| {name: competition.name, value: competition.id}}
    titles = Competition.search(params[:query], fields: [{name: :text_start}], limit: 10).map {|competition| {store: competition.name, value: competition.id}}
    authors = Competition.search(params[:query], fields: [{collegename: :text_start}], limit: 10).map {|competition| {store: competition.collegename, value: competition.id}}
    #categ = Competition.search(params[:query], fields: [{category: :text_start}], limit: 10).map {|competition| {store: competition.category, value: competition.id}}
    render json: (titles + authors )

  end

  def index
    
    #@block_facets = Block.facets_default(params)

    if params[:query].present?
      @competitions = Competition.search(params[:query],fields: [:name,:collegename,:category], facets: [:category] ,page: params[:page])
         
    else
      @competitions = Competition.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
      #Nothing there @users = User.search "*",limit: 200
      
    end

    if params[:search].present?
      @competitions = Competition.near(params[:search], 50000).paginate(:page => params[:page], :per_page => 15)
    end

    @compFacet = Competition.facets_search(params)
    #debugger

    respond_with(@competitions)
  end

  def show
    respond_with(@competition)
  end

  def new

      @competition = current_user.competitions.build
      respond_with(@competition)
    
  end

  def edit
    @competition = Competition.find(params[:id])

  end

  def create
    @competition = current_user.competitions.new(competition_params)
    @competition.save
    respond_with(@competition)
  end

  def update
    @competition.update(competition_params)
    respond_with(@competition)
  end

  def destroy
    @competition.destroy
    respond_with(@competition)
  end

  def participants
    @title = "Following"
    @comp  = Competition.find(params[:id])
  end

  def follow(other_comp)
    meetings.create(attending_competition: other_comp.id)
  end

  

  private

    def set_competition
      @competition = Competition.find(params[:id])
      @id=@competition.id

      #Rails.logger.info "The ID"
      #Rails.logger.info params[@id]
    end

    

    def correct_user
        @competition = current_user.competitions.find_by(id: params[:id])
        redirect_to competitions_path, notice: "Not authorized to edit this pin" if @competition.nil?

    end

    def competition_params
      params.require(:competition).permit(:name,:category, :description, :collegename, 
        :money, :onOff,:location,:startDate,:endDate,:organizedBy,:linkWebsite,:linkWebsite,:linkFb,:startDateText,:endDateText,:latitude,
        :longitude)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<div class="formssComp container">
  <div id="wrapper">
      <div id="box">  
        <div class="header">
          <h4><strong>Enter Competition Details</strong></h4>
        </div>
          



          <%= form_for(@competition) do |f| %>
              <% if @competition.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

                  <ul>
                  <% @competition.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>


              <h5>EVENT NAME *</h5>
              <%= f.text_field :name, autofocus: true, class: "form-control" , :placeholder => "eg. Quizzical", :autocomplete => :off%>

              <h5>EVENT CATEGORY *</h5>
              <div class="backg">
                  <%= f.select :category, 
                  options_for_select([ ['Bussiness Plan','Bussiness Plan'],['Dance','Dance'],['Design','Design'],['Debate','Debate'],['Electronics','Electronics'],['Law','Law'],['Management','Management'],['MUN','MUN'],['Presentation','Presentation'],['Programming','Programming'],['Robotics','Robotics'],['Sports','Sports'],['Strategy','Strategy'],['Miscellaneous','Miscellaneous']   ], :selected => @competition.category),{}, { :class => 'span3 controls controls-row select-style' } %>
              </div>

              <h5>BRIEF DESCRIPTION *</h5>
              <%= f.text_field :description, class: "form-control" , :placeholder => "A Bussiness and Economy Quiz", :autocomplete => :off%>

            
              <h5>COLLEGE / COMPANY NAME</h5>
              <%= f.text_field :collegename, class: "form-control" , :placeholder => "Adobe",:autocomplete => :off%>

              <h5>ORGANIZED BY</h5>
              <%= f.text_field :organizedBy, class: "form-control",  :placeholder => "The Quiz Club at Adobe  |  [Fest name/Club name/Fete name]" ,:autocomplete => :off%>

              <h5>LOCATION</h5>
              <%= f.text_field :location, id: "competition_location", class: "form-control", autocomplete: :off%>
            

              <h5>ONLINE/ONSITE EVENT</h5>
              <div class="backg">
                 <%= f.select :onOff, 
                options_for_select([['Onsite','Onsite'],['Online','Online']  ], :selected => @competition.category),{}, { :class => 'span3 controls controls-row select-style' } %>
               </div>
   

              <h5>TOTAL PRIZE MONEY[Rupees]</h5>
              <div class="prizeMoney">
                <input class="form-control"  type="number" name="competition[money]" id="competition_money"
                    min="0" max="100000" step="1000" maxlength="6" >
              </div>

              <h5>WEBSITE</h5>
              <%= f.text_field :linkWebsite, class: "form-control", :placeholder => "Enter the link of the events website"%>

              <h5>FB PAGE</h5>
              <%= f.text_field :linkFb, class: "form-control", :placeholder => "Enter the link of the events FB page" %>

              
               <h5>STARTS AT *</h5>
               
              <div class="y">
                  <div class="x">
                      <%= f.text_field :startDateText, class: "form-control" %>
                  </div>
              </div>


              <h5>ENDS AT</h5>
              <div class="y">
                  <div class="x">
                      <%= f.text_field :endDateText, class: "form-control" %>
                  </div>
              </div>
              



              <%= f.submit class: "btn btn-primary" %>


    
          <% end %>

      </div>
     
    </div>
</div>



             

app/views/competitions/_register.html.erb
<%= form_for(current_user.meetings.build,remote: true) do |f| %>

  <div><%= hidden_field_tag :attending_competition_id, @competition.id %></div>
  <%= f.submit "Register",{ :class=>"buttonn" } %>

<% end %>

app/views/competitions/_register_form.html.erb
<div id="register_form">
	<% if user_signed_in? %>
	  <% if current_user.attending_competitions.include?(@competition) %>
	    <%= render 'unregister' %>
	  <% else %>
	    <%= render 'register' %>
	  <% end %>
	<% else %>
		<div class="registerevent">
		        
			<div id="wrapper">
			    	<div id="box">
			        	<div id="top_header">
			          		
			          		<h5>Register for the event</h5>
			        	</div>
			        
				        <div id="inputs">

							<%= form_tag("/meetings/register", :method=>"post") do %>
								<div><%= hidden_field_tag :attending_competition_id, @competition.id %></div>
								<%= text_field_tag :todo_text, params[:todo_text],class: "form-control" ,:placeholder =>"Email", autocomplete: "off"%>
							  


							  <%= submit_tag("Register", :class=>"btn registerButton") %>
							<% end %>
		        
	        			</div><!-- inputs end -->
    				</div><!--box ends -->

    		</div><!--wrapper ends -->
		</div><!-- register event ends -->

	<% end %>

 </div>

app/views/competitions/_unregister.html.erb
<%= form_for(current_user.meetings.find_by(attending_competition_id: @competition.id),html: { method: :delete },remote: true) do |f| %>

  <%= f.submit "Unregister",{ :class=>"buttonn" }%>

<% end %>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<div class="wrapper">
  <div class="section group">
    <div class="col span_1_of_3">
    
        



        <div class="field" >
            <%= form_tag competitions_path, :method => :get do %>
          
                <%= text_field_tag :search, params[:search],id: "address",class: "form-control" ,:placeholder =>"Search nearby...", autocomplete: "off"%>

                <button type="submit" class="pull-right" id="search">Search Near!</button>
              
            <% end %>
          
        </div><!-- search form over -->
        
         

        <div class="facets">
          <nav>
            <ul>
              <% if @compFacet.facets["category"].present? %>
                  <% @compFacet.facets["category"]["terms"].each do |filter| %>
                    <% unless filter['term'].blank? || filter['term'] == '0' || filter['term'] == 0 %>
                      <li><%= link_to "#{filter["term"]} (#{filter["count"]})", "/competitions?query=#{filter["term"]}" %></li>
                    <% end %>
                  <% end %>
              <% end %>
            </ul>
          </nav>
        </div><!-- facets over -->

    </div><!-- colspan 1/3 over -->

    <div class="col span_2_of_3">
  
        <div id="comp" class="transitions-enabled">
            <% @competitions.each do |competition| %>
              
                <div class="thumbnail masonry-item ">
                    <div class="topp">
                    </div>

                    <div class="caption">
                        <!-- <h4 class="pull-right">$64.99</h4> -->
                        <h4><%= link_to "#{competition.name}".upcase, competition %>
                        </h4>
                        <%= competition.description %><br/>
                       
                       <h5 ><span class="glyphicon glyphicon-tag"></span>  <strong><%= competition.category %></strong></h5>
                        
                        <h5 class="pull-left"><span class="glyphicon glyphicon-calendar"></span>  <%= competition.startDateText %></h5>
                        
                        <h5 style="color:black" class="truncate"><span class="glyphicon glyphicon-map-marker"></span> <%= competition.location %> </h5> 
                    </div>


                    <div class="footer">
                        <hr style='background-color:#000000;border-width:0;color:#000000;height:1px;line-height:0;text-align:left;width:95%;'/>
                        <p class="pull-right moreInfo"><%= link_to 'More Info', competition %></p>      
                    </div>


                  </div>
               
            
            <% end %>
        </div>


    </div>
  </div>
</div>

 



  









    
   <div class="center">
     <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>

app/views/competitions/new.html.erb
	<%= render 'form' %>


<%= link_to 'Back', competitions_path %>

app/views/competitions/participants.html.erb
<div class="container participant">
			
	<h1 id="title">Participants</h1>
	<ul id="list">
	
		<% @comp.meetings.each do |user| %>

				<% unless  user.email.blank? %>
						<li><%= user.email %><br/> </li>
						<!--The case where the email is not set because it is a relation of id's waala meeting-->
				<% end %>
					        	
		      	     	    	  
	    <% end %>


	    <% @comp.participants.each do |user| %>

				<li><%= user.email %><br/> </li>	        	
		      		     	    	  
	    <% end %>



	</ul>
</div>
			

app/views/competitions/show.html.erb
<div class="showbody">
	<div class="container">

		<div class="row" id="moreInfo">
			<div class="col-sm-6">
				<div class="boxed center">
					<strong><h1 class="thetitle centre"><%= "#{@competition.name}".upcase %></h1></strong>
				</div>
				<p style="border-style:solid; border-color:#FF0000;" class="redline"></p>

				<div class="tabbable">
					<ul class="nav nav-tabs">
						<li class="active"><a href="#tab1" data-toggle="tab">Where</a></li>	
						<li><a href="#tab2" data-toggle="tab">Schedule</a></li>
								
					</ul>
					<div class="tab-content">
						<div class="tab-pane" id="tab2">
							<h4>Logo</small></h4>
							
							<img src="http://placehold.it/140" class="thumbnail pull-left" alt="Placeholder image">
							
							
							
						    <h4><p><%= @competition.description %></p></h4>	
						  	

							<hr>
							<p>Starts at : <%= @competition.startDateText %> </p>
							<% unless   @competition.endDateText.empty? %>
								<p>Ends at : <%= @competition.endDateText %> </p>
							<% end %>
							
							
						</div><!-- end tab-pane -->
						<div class="tab-pane active" id="tab1">
							<h4><span class="glyphicon glyphicon-map-marker"></span> Our Location </h4>
							
							<iframe width="100%" height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/?q=<%= @competition.location %>&output=embed"></iframe>
							
							<p><h4><%= @competition.location %></h4></p>
						</div><!-- end tab-pane -->
						
						
					</div><!-- end tab-content -->
				</div><!-- end tabbable -->

			</div>
			<div class="col-sm-6">
				<div class="details">

					<header>
						<h1>ESSENTIAL DETAILS</h1>
						 
					</header>

					<ul>
					  	
						  <li class="question">
						    <h3><span class=" glyphicon glyphicon-tag glyphicon1"></span> <p><%= @competition.category %></p></h3>						
						  </li>
					

						  
						  <% unless   @competition.onOff.empty? %>
							  <li class="question">
							    <h3><span class="glyphicon3 glyphicon glyphicon-map-marker"><p><%= @competition.onOff %></p></h3>							
							  </li>
						  <% end %>

						  <% unless   @competition.money.nil? %>
							  <li class="question">
							    <h3><i class="fa fa-fw fa-money"></i><p><%= @competition.money %></p></h3>							
							  </li>
						  <% end %>

						  <% unless   @competition.organizedBy.empty? %>
							  <li class="question">
							    <h3><i class="fa fa-server glyphicon4"></i><p><%= @competition.organizedBy %></p></h3>						
							  </li>
						  <% end %>
						   <% unless   @competition.collegename.empty? %>
							  <li class="question">
							    <h3><i class="glyphicon glyphicon-home glyphicon4"></i><p><%= @competition.collegename %></p></h3>						
							  </li>
						  <% end %>
						   

						  <% unless   @competition.linkFb.empty? %>
							  <li class="question">
							    <h3><i class="fa fa-fw fa-facebook glyphicon5"></i><p><%= @competition.linkFb %></p></h3>							
							  </li>
						  <% end %>

						  <% unless   @competition.linkWebsite.empty? %>
							  <li class="question">
							    <h3><span class=" glyphicon glyphicon6 glyphicon-link"><p><%= @competition.linkWebsite %></p></h3>							
							  </li>
						  <% end %>

					</ul>
					<!-- <button class="button-submit" onclick="calcResults('.form')">SAVE THIS EVENT</button> -->

				</div><!-- details end -->
				
			</div><!-- end col-sm-6 -->
					
		</div>


		 	
		
	</div><!--container-->

	
	<div class="thebuttons registerthing">
        	
				
		<div class="box bg-1 ">
			
			<%= render 'register_form' %>
		</div>
				
			
        			
    </div>

	<div class="thebuttons">
	        <section class="content">
					
					<div class="box bg-1 ">
						<% if @competition.user == current_user %>
							<%= link_to 'Edit', edit_competition_path(@competition),{ :class=>"buttonn" } %>
							<%= link_to 'Participants', participants_competition_path,{ :class=>"buttonn" }%>
						<% end %>
						<%= link_to 'BACK', competitions_path ,{ :class=>"buttonn" }%>
            
					</div>
					
				</section>
	    </div>
	    
</div><!--showbody-->