config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
resources :competitions do
    collection do
      get :autocomplete
    end
  end
  resources :competitions do
    member do
      get :participants
    end
  end

match "meetings/register" => "meetings#register", :via => :post

devise_for :users, controllers: { sessions: "users/sessions",registrations: "users/registrations",confirmations: "users/confirmations",passwords: "users/passwords",unlocks: "users/unlocks" }
resources :users, :only => [:show] 

  match '/users/:id/attending_competitions', :to => 'users#attending_competitions', :via => [:get,:post] , as: 'attending_competitions'
  match '/users/:id/created_competitions', :to => 'users#created_competitions', :via => [:get,:post] , as: 'created_competitions'

  root 'pages#home'

  resources :meetings,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
 <div class="landingPage">
     <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                    <div class="row">
                        <div class="footer-col col-md-4">
                        <h3>Suggestions?</h3>
                        <p>Mail us at: support@compete.com</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>

                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>About Cmpete</h3>
                        <p>Cmpete is a f</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Cmpete.com 2015
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default ">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CMPETE!", competitions_path ,{class: "navbar-brand upMargin headerFont"}%>
    </div>
    
    <div class="headerfield navbar-form navbar-left input-group" id="searchform">
      <%= form_tag competitions_path, :method => :get do %>
        <%= text_field_tag :query, params[:query], id: "competition_search", :placeholder => "Search by competition name,college ...", class: "form-control", autocomplete: "off" %>
        <button type="submit" id="search" class="hidden">Find!</button>
      <% end %>
    </div>
    

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
      
      <ul class="nav navbar-nav navbar-right">

        <li class="upMargin">
          <p class="createComp"><a href="/competitions/new" class="btn btn-success btn-small" background-color="#2ecc71"><font color="white" class="headerFont">Create Competition</font></a> </p></li>
        

        <% if user_signed_in? %>
          <li class="upMargin headerFont"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li class="dropdown upMargin headerFont">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Me<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
           <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Registered Contests", attending_competitions_path(current_user.id) %></li> 
            <li class="divider"></li>
            <li><%= link_to "Created Contests", created_competitions_path(current_user.id) %></li> 

          </ul>
        </li>
        <% else %>
          <li class="upMargin headerFont"><a href="/users/sign_up">Sign up</a></li>
          <li class="upMargin headerFont"><a href="/users/sign_in">Log in</a></li>
        <% end %>
         
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Protone1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&libraries=places&language=en-US"></script>
  
  <script type="text/javascript" src="https://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>

  <script type="text/javascript" src="https://rawgithub.com/sgruhier/typeahead-addresspicker/master/dist/typeahead-addresspicker.js"></script>

  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
  <%= render "layouts/header" unless @skip_header %>
  <div class="flash-message">
    <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-success alert-block alert-dismissible") %>
    <% end %>
  </div>

    <%= yield %>

  <%= render "layouts/footer" unless @skip_footer %>

</body>
</html>